### PR TITLE
FORMIT-12642: Improvements to 3D Context Creator plugin

### PR DESCRIPTION
**Pull request by josh-goldstein-adsk**
This PR includes several improvements to the 3D Context Creator plugin, including:

- Report the current project location, if set (and indicate if it's not set)
- Include a button to set the location instead of saying "Click the toolbar button"
- Indicate whether the location is set or not, and prevent generating context without a selection
- Use the size of the satellite image to determine radius, and eliminate the radius slider
- Remove lat/long numbers
- Rename the button "Create 3D Context"
- Add an attribute to the context instance, and delete existing context instance if it exists
- Add the context instance to a layer
- Update success message to indicate how to control context visibility

Here's what the plugin looks like with no location set:
image

Here's what the plugin looks like with a location set:
image

### CODE REVIEW

**Comment by josh-goldstein-adsk** [comment]
Hi @h-iL @StudioLE @martinstacey I wasn't able to add you as reviewers, but can you take a look?

**Comment by martinstacey** [comment]
LGTM!

**Review by h-iL — APPROVED** [review]
Looks great, just approved please feel free to merge :)

**Comment by josh-goldstein-adsk** [comment]
@h-iL thanks, but I'm not sure I have the ability to merge. The only options I have are "Close with comment" and "Comment." Can someone merge for me?

**Pull request merged**
